kind: Service
apiVersion: v1
metadata:
  name: massage-service
  labels:
    app: massage-service
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster
  type: ClusterIP

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: massageapp

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    # - nodePort: 32767
    - port: 50150
      targetPort: 50150
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: massage-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: massageapp
  template:
    metadata:
      labels:
        app: massageapp
    spec:
      containers:
        - name: massageapp-container
          image: yuxuanleoli/recipe-backend:1.0
          ports:
            - containerPort: 50150
