FROM node:14-alpine3.16 AS node-frontend

WORKDIR /app

# Explicitly copy over package.json files
COPY package.json package.json
COPY ./massage-website-frontend/package.json ./massage-website-frontend/package.json

# Copy over UI content
COPY ./massage-website-frontend ./massage-website-frontend

# Install prod dependencies
RUN apk add yarn
RUN yarn
RUN yarn build

# The base go-image
FROM nginx:latest AS deploy

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=node-frontend /app/massage-website-frontend/public .

CMD [ "nginx", "-g", "daemon off;" ]