version: "3.9"

services:
  
  massagewebsite-frontend: 
    container_name: massagewebsite-frontend
    image: yuxuanleoli/massagewebsite-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    network_mode: host
  
  massagewebsite-backend: 
    container_name: massagewebsite-backend
    image: yuxuanleoli/massagewebsite-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "65535:65535"
    environment:
      - NODE_ENV=production
    network_mode: host